---
spring:
  http:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: testpwd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 7000
logging:
  level:
      javatraining: DEBUG
      org:
        springframework: INFO
---
spring:
  profiles: docker
server:
  port: 8080
---
spring:
  profiles: dev
  jackson:
    serialization:
      indent_output: true
logging:
  level:
    javatraining: DEBUG

bd:
  dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
  format-sql: true
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/websystique
  username: root
  password: testpwd